FROM alpine:latest

LABEL "com.github.actions.name"="Hello"
LABEL "com.github.actions.icon"="filter"
LABEL "com.github.actions.color"="yellow"

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
